'''
Author  : Edward Daniel Nichols
Date    : May 8th, 2018 AD

PD3D, Institute for Simulation and Training
University of Central Florida

To the purveyor of this program:
Prepare yourself, poor soul. I cannot explain the suffering, the torment and the frustration that has been wrought here.
Surely, since you are here, there is more to come. If there is anything I can do to alleviate your burden, feel free to summon me.
They will know how. The least I can do is help those who come after me, to navigate this endless, needlessly convoluted, and extravagantly hideous labyrinth.
Feel free to curse me, for this is likely to be the worst thing you've ever seen.

To self:
You did this to yourself.
Welcome to Hell.
'''
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class GUI(object):

    def __init__(self, ControlSystem):

        # ---------------------------------------------------- #
        # Create the main window and set the geometry:
        ControlSystem.setObjectName("ControlSystem")
        ControlSystem.resize(1000, 850)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ControlSystem.sizePolicy().hasHeightForWidth())
        ControlSystem.setSizePolicy(sizePolicy)
        ControlSystem.setMinimumSize(QtCore.QSize(1000, 850))
        ControlSystem.setLayoutDirection(QtCore.Qt.LeftToRight)
        ControlSystem.setAutoFillBackground(False)
        ControlSystem.setStyleSheet("background: rgb(255, 255, 255);")
        self.windowLayout = QtWidgets.QVBoxLayout(ControlSystem)
        self.windowLayout.setObjectName("windowLayout")

        # ---------------------------------------------------- #
        # Create the primary grid within the main window:
        self.primaryGrid = QtWidgets.QGridLayout()
        self.primaryGrid.setSpacing(10)
        self.primaryGrid.setObjectName("primaryGrid")

        # ---------------------------------------------------- #
        # Predefine some basic parameters:
        greybg = "background: rgba(240, 240, 240, 220);"

        btnfont = QtGui.QFont()
        btnfont.setFamily("Yu Gothic UI")
        btnfont.setPointSize(12)
        btnfont.setBold(False)
        btnfont.setWeight(50)

        titleFont = QtGui.QFont()
        titleFont.setFamily("Yu Gothic UI")
        titleFont.setPointSize(26)
        titleFont.setBold(True)
        titleFont.setWeight(75)

        # ---------------------------------------------------- #
        # Grid for Room 1:
        self.gridR1 = QtWidgets.QGridLayout()
        self.gridR1.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridR1.setContentsMargins(10, 10, 10, 10)
        self.gridR1.setSpacing(10)
        self.gridR1.setObjectName("gridR1")

        self.StatusR1 = QtWidgets.QPushButton(ControlSystem)
        self.StatusR1.setMinimumSize(QtCore.QSize(150, 25))
        self.StatusR1.setFont(btnfont)
        self.StatusR1.setStyleSheet(greybg)
        self.StatusR1.setCheckable(True)
        self.StatusR1.setObjectName("StatusR1")
        self.gridR1.addWidget(self.StatusR1, 2, 0, 1, 2)

        self.Int1R1 = QtWidgets.QPushButton(ControlSystem)
        self.Int1R1.setMinimumSize(QtCore.QSize(50, 25))
        self.Int1R1.setFont(btnfont)
        self.Int1R1.setStyleSheet(greybg)
        self.Int1R1.setObjectName("Int1R1")
        self.gridR1.addWidget(self.Int1R1, 3, 0, 1, 1)

        self.Int2R1 = QtWidgets.QPushButton(ControlSystem)
        self.Int2R1.setMinimumSize(QtCore.QSize(50, 25))
        self.Int2R1.setFont(btnfont)
        self.Int2R1.setStyleSheet(greybg)
        self.Int2R1.setObjectName("Int2R1")
        self.gridR1.addWidget(self.Int2R1, 3, 1, 1, 1)

        self.selectPanelR1 = QtWidgets.QComboBox(ControlSystem)
        self.selectPanelR1.setMinimumSize(QtCore.QSize(150, 25))
        self.selectPanelR1.setFont(btnfont)
        self.selectPanelR1.setStyleSheet(greybg)
        self.selectPanelR1.setObjectName("selectPanelR1")
        for i in range(0, 10):
            self.selectPanelR1.addItem("")
        self.gridR1.addWidget(self.selectPanelR1, 1, 0, 1, 2)

        self.room1 = QtWidgets.QLabel(ControlSystem)
        self.room1.setMinimumSize(QtCore.QSize(150, 150))
        self.room1.setMaximumSize(QtCore.QSize(16777215, 200))
        self.room1.setFont(titleFont)
        self.room1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room1.setScaledContents(False)
        self.room1.setAlignment(QtCore.Qt.AlignCenter)
        self.room1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room1.setObjectName("room1")
        self.gridR1.addWidget(self.room1, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.gridR1, 0, 1, 1, 1)


        self.p2grid = QtWidgets.QGridLayout()
        self.p2grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.p2grid.setContentsMargins(10, 10, 10, 10)
        self.p2grid.setSpacing(10)
        self.p2grid.setObjectName("p2grid")
        self.p2Int2 = QtWidgets.QPushButton(ControlSystem)
        self.p2Int2.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p2Int2.setFont(font)
        self.p2Int2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p2Int2.setObjectName("p2Int2")
        self.p2grid.addWidget(self.p2Int2, 3, 1, 1, 1)
        self.p2Int1 = QtWidgets.QPushButton(ControlSystem)
        self.p2Int1.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p2Int1.setFont(font)
        self.p2Int1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p2Int1.setObjectName("p2Int1")
        self.p2grid.addWidget(self.p2Int1, 3, 0, 1, 1)
        self.p2Status = QtWidgets.QPushButton(ControlSystem)
        self.p2Status.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p2Status.setFont(font)
        self.p2Status.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p2Status.setCheckable(True)
        self.p2Status.setObjectName("p2Status")
        self.p2grid.addWidget(self.p2Status, 2, 0, 1, 2)
        self.p2SelectPanel = QtWidgets.QComboBox(ControlSystem)
        self.p2SelectPanel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p2SelectPanel.setFont(font)
        self.p2SelectPanel.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p2SelectPanel.setObjectName("p2SelectPanel")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2SelectPanel.addItem("")
        self.p2grid.addWidget(self.p2SelectPanel, 1, 0, 1, 2)
        self.room2 = QtWidgets.QLabel(ControlSystem)
        self.room2.setMinimumSize(QtCore.QSize(150, 150))
        self.room2.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.room2.setFont(font)
        self.room2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room2.setAlignment(QtCore.Qt.AlignCenter)
        self.room2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room2.setObjectName("room2")
        self.p2grid.addWidget(self.room2, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.p2grid, 0, 2, 1, 1)

        self.p3grid = QtWidgets.QGridLayout()
        self.p3grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.p3grid.setContentsMargins(10, 10, 10, 10)
        self.p3grid.setSpacing(10)
        self.p3grid.setObjectName("p3grid")
        self.p3Int2 = QtWidgets.QPushButton(ControlSystem)
        self.p3Int2.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p3Int2.setFont(font)
        self.p3Int2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p3Int2.setObjectName("p3Int2")
        self.p3grid.addWidget(self.p3Int2, 3, 1, 1, 1)
        self.p3Int1 = QtWidgets.QPushButton(ControlSystem)
        self.p3Int1.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p3Int1.setFont(font)
        self.p3Int1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p3Int1.setObjectName("p3Int1")
        self.p3grid.addWidget(self.p3Int1, 3, 0, 1, 1)
        self.p3Status = QtWidgets.QPushButton(ControlSystem)
        self.p3Status.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p3Status.setFont(font)
        self.p3Status.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p3Status.setCheckable(True)
        self.p3Status.setObjectName("p3Status")
        self.p3grid.addWidget(self.p3Status, 2, 0, 1, 2)
        self.p3SelectPanel = QtWidgets.QComboBox(ControlSystem)
        self.p3SelectPanel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p3SelectPanel.setFont(font)
        self.p3SelectPanel.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p3SelectPanel.setObjectName("p3SelectPanel")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3SelectPanel.addItem("")
        self.p3grid.addWidget(self.p3SelectPanel, 1, 0, 1, 2)
        self.room3 = QtWidgets.QLabel(ControlSystem)
        self.room3.setMinimumSize(QtCore.QSize(150, 150))
        self.room3.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.room3.setFont(font)
        self.room3.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room3.setAlignment(QtCore.Qt.AlignCenter)
        self.room3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room3.setObjectName("room3")
        self.p3grid.addWidget(self.room3, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.p3grid, 0, 3, 1, 1)



        self.p5grid = QtWidgets.QGridLayout()
        self.p5grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.p5grid.setContentsMargins(10, 10, 10, 10)
        self.p5grid.setSpacing(10)
        self.p5grid.setObjectName("p5grid")
        self.p5Int2 = QtWidgets.QPushButton(ControlSystem)
        self.p5Int2.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p5Int2.setFont(font)
        self.p5Int2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p5Int2.setObjectName("p5Int2")
        self.p5grid.addWidget(self.p5Int2, 3, 1, 1, 1)
        self.p5Int1 = QtWidgets.QPushButton(ControlSystem)
        self.p5Int1.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p5Int1.setFont(font)
        self.p5Int1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p5Int1.setObjectName("p5Int1")
        self.p5grid.addWidget(self.p5Int1, 3, 0, 1, 1)
        self.p5Status = QtWidgets.QPushButton(ControlSystem)
        self.p5Status.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p5Status.setFont(font)
        self.p5Status.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p5Status.setCheckable(True)
        self.p5Status.setObjectName("p5Status")
        self.p5grid.addWidget(self.p5Status, 2, 0, 1, 2)
        self.p5SelectPanel = QtWidgets.QComboBox(ControlSystem)
        self.p5SelectPanel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p5SelectPanel.setFont(font)
        self.p5SelectPanel.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p5SelectPanel.setObjectName("p5SelectPanel")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5SelectPanel.addItem("")
        self.p5grid.addWidget(self.p5SelectPanel, 1, 0, 1, 2)
        self.room5 = QtWidgets.QLabel(ControlSystem)
        self.room5.setMinimumSize(QtCore.QSize(150, 150))
        self.room5.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.room5.setFont(font)
        self.room5.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room5.setAlignment(QtCore.Qt.AlignCenter)
        self.room5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room5.setObjectName("room5")
        self.p5grid.addWidget(self.room5, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.p5grid, 1, 2, 1, 1)
        self.p4grid = QtWidgets.QGridLayout()
        self.p4grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.p4grid.setContentsMargins(10, 10, 10, 10)
        self.p4grid.setSpacing(10)
        self.p4grid.setObjectName("p4grid")
        self.p4Int2 = QtWidgets.QPushButton(ControlSystem)
        self.p4Int2.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p4Int2.setFont(font)
        self.p4Int2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p4Int2.setObjectName("p4Int2")
        self.p4grid.addWidget(self.p4Int2, 3, 1, 1, 1)
        self.p4Int1 = QtWidgets.QPushButton(ControlSystem)
        self.p4Int1.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p4Int1.setFont(font)
        self.p4Int1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p4Int1.setObjectName("p4Int1")
        self.p4grid.addWidget(self.p4Int1, 3, 0, 1, 1)
        self.p4Status = QtWidgets.QPushButton(ControlSystem)
        self.p4Status.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p4Status.setFont(font)
        self.p4Status.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p4Status.setCheckable(True)
        self.p4Status.setObjectName("p4Status")
        self.p4grid.addWidget(self.p4Status, 2, 0, 1, 2)
        self.p4SelectPanel = QtWidgets.QComboBox(ControlSystem)
        self.p4SelectPanel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p4SelectPanel.setFont(font)
        self.p4SelectPanel.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p4SelectPanel.setObjectName("p4SelectPanel")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4SelectPanel.addItem("")
        self.p4grid.addWidget(self.p4SelectPanel, 1, 0, 1, 2)
        self.room4 = QtWidgets.QLabel(ControlSystem)
        self.room4.setMinimumSize(QtCore.QSize(150, 150))
        self.room4.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.room4.setFont(font)
        self.room4.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room4.setAlignment(QtCore.Qt.AlignCenter)
        self.room4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room4.setObjectName("room4")
        self.p4grid.addWidget(self.room4, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.p4grid, 1, 1, 1, 1)
        self.p6grid = QtWidgets.QGridLayout()
        self.p6grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.p6grid.setContentsMargins(10, 10, 10, 10)
        self.p6grid.setSpacing(10)
        self.p6grid.setObjectName("p6grid")
        self.p6Int2 = QtWidgets.QPushButton(ControlSystem)
        self.p6Int2.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p6Int2.setFont(font)
        self.p6Int2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p6Int2.setObjectName("p6Int2")
        self.p6grid.addWidget(self.p6Int2, 3, 1, 1, 1)
        self.p6Int1 = QtWidgets.QPushButton(ControlSystem)
        self.p6Int1.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p6Int1.setFont(font)
        self.p6Int1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p6Int1.setObjectName("p6Int1")
        self.p6grid.addWidget(self.p6Int1, 3, 0, 1, 1)
        self.p6Status = QtWidgets.QPushButton(ControlSystem)
        self.p6Status.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p6Status.setFont(font)
        self.p6Status.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p6Status.setCheckable(True)
        self.p6Status.setObjectName("p6Status")
        self.p6grid.addWidget(self.p6Status, 2, 0, 1, 2)
        self.p6SelectPanel = QtWidgets.QComboBox(ControlSystem)
        self.p6SelectPanel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p6SelectPanel.setFont(font)
        self.p6SelectPanel.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p6SelectPanel.setObjectName("p6SelectPanel")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6SelectPanel.addItem("")
        self.p6grid.addWidget(self.p6SelectPanel, 1, 0, 1, 2)
        self.room6 = QtWidgets.QLabel(ControlSystem)
        self.room6.setMinimumSize(QtCore.QSize(150, 150))
        self.room6.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.room6.setFont(font)
        self.room6.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room6.setAlignment(QtCore.Qt.AlignCenter)
        self.room6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room6.setObjectName("room6")
        self.p6grid.addWidget(self.room6, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.p6grid, 1, 3, 1, 1)
        self.p7grid = QtWidgets.QGridLayout()
        self.p7grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.p7grid.setContentsMargins(10, 10, 10, 10)
        self.p7grid.setSpacing(10)
        self.p7grid.setObjectName("p7grid")
        self.p7Int2 = QtWidgets.QPushButton(ControlSystem)
        self.p7Int2.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p7Int2.setFont(font)
        self.p7Int2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p7Int2.setObjectName("p7Int2")
        self.p7grid.addWidget(self.p7Int2, 3, 1, 1, 1)
        self.p7Int1 = QtWidgets.QPushButton(ControlSystem)
        self.p7Int1.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p7Int1.setFont(font)
        self.p7Int1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p7Int1.setObjectName("p7Int1")
        self.p7grid.addWidget(self.p7Int1, 3, 0, 1, 1)
        self.p7Status = QtWidgets.QPushButton(ControlSystem)
        self.p7Status.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p7Status.setFont(font)
        self.p7Status.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p7Status.setCheckable(True)
        self.p7Status.setObjectName("p7Status")
        self.p7grid.addWidget(self.p7Status, 2, 0, 1, 2)
        self.p7SelectPanel = QtWidgets.QComboBox(ControlSystem)
        self.p7SelectPanel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p7SelectPanel.setFont(font)
        self.p7SelectPanel.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p7SelectPanel.setObjectName("p7SelectPanel")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7SelectPanel.addItem("")
        self.p7grid.addWidget(self.p7SelectPanel, 1, 0, 1, 2)
        self.room7 = QtWidgets.QLabel(ControlSystem)
        self.room7.setMinimumSize(QtCore.QSize(150, 150))
        self.room7.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.room7.setFont(font)
        self.room7.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room7.setAlignment(QtCore.Qt.AlignCenter)
        self.room7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room7.setObjectName("room7")
        self.p7grid.addWidget(self.room7, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.p7grid, 2, 1, 1, 1)
        self.p9grid = QtWidgets.QGridLayout()
        self.p9grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.p9grid.setContentsMargins(10, 10, 10, 10)
        self.p9grid.setSpacing(10)
        self.p9grid.setObjectName("p9grid")
        self.p9Int1 = QtWidgets.QPushButton(ControlSystem)
        self.p9Int1.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p9Int1.setFont(font)
        self.p9Int1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p9Int1.setObjectName("p9Int1")
        self.p9grid.addWidget(self.p9Int1, 3, 0, 1, 1)
        self.p9Int2 = QtWidgets.QPushButton(ControlSystem)
        self.p9Int2.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p9Int2.setFont(font)
        self.p9Int2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p9Int2.setObjectName("p9Int2")
        self.p9grid.addWidget(self.p9Int2, 3, 1, 1, 1)
        self.p9Status = QtWidgets.QPushButton(ControlSystem)
        self.p9Status.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p9Status.setFont(font)
        self.p9Status.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p9Status.setCheckable(True)
        self.p9Status.setObjectName("p9Status")
        self.p9grid.addWidget(self.p9Status, 2, 0, 1, 2)
        self.p9SelectPanel = QtWidgets.QComboBox(ControlSystem)
        self.p9SelectPanel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p9SelectPanel.setFont(font)
        self.p9SelectPanel.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p9SelectPanel.setObjectName("p9SelectPanel")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9SelectPanel.addItem("")
        self.p9grid.addWidget(self.p9SelectPanel, 1, 0, 1, 2)
        self.room9 = QtWidgets.QLabel(ControlSystem)
        self.room9.setMinimumSize(QtCore.QSize(150, 150))
        self.room9.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.room9.setFont(font)
        self.room9.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room9.setAlignment(QtCore.Qt.AlignCenter)
        self.room9.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room9.setObjectName("room9")
        self.p9grid.addWidget(self.room9, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.p9grid, 2, 3, 1, 1)
        self.p8grid = QtWidgets.QGridLayout()
        self.p8grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.p8grid.setContentsMargins(10, 10, 10, 10)
        self.p8grid.setSpacing(10)
        self.p8grid.setObjectName("p8grid")
        self.p8Int2 = QtWidgets.QPushButton(ControlSystem)
        self.p8Int2.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p8Int2.setFont(font)
        self.p8Int2.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p8Int2.setObjectName("p8Int2")
        self.p8grid.addWidget(self.p8Int2, 3, 1, 1, 1)
        self.p8Int1 = QtWidgets.QPushButton(ControlSystem)
        self.p8Int1.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p8Int1.setFont(font)
        self.p8Int1.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p8Int1.setObjectName("p8Int1")
        self.p8grid.addWidget(self.p8Int1, 3, 0, 1, 1)
        self.p8Status = QtWidgets.QPushButton(ControlSystem)
        self.p8Status.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p8Status.setFont(font)
        self.p8Status.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p8Status.setCheckable(True)
        self.p8Status.setObjectName("p8Status")
        self.p8grid.addWidget(self.p8Status, 2, 0, 1, 2)
        self.p8SelectPanel = QtWidgets.QComboBox(ControlSystem)
        self.p8SelectPanel.setMinimumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.p8SelectPanel.setFont(font)
        self.p8SelectPanel.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p8SelectPanel.setObjectName("p8SelectPanel")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8SelectPanel.addItem("")
        self.p8grid.addWidget(self.p8SelectPanel, 1, 0, 1, 2)
        self.room8 = QtWidgets.QLabel(ControlSystem)
        self.room8.setMinimumSize(QtCore.QSize(150, 150))
        self.room8.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.room8.setFont(font)
        self.room8.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.room8.setAlignment(QtCore.Qt.AlignCenter)
        self.room8.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.room8.setObjectName("room8")
        self.p8grid.addWidget(self.room8, 0, 0, 1, 2)
        self.primaryGrid.addLayout(self.p8grid, 2, 2, 1, 1)

        self.controlLayout = QtWidgets.QVBoxLayout()
        self.controlLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.controlLayout.setSpacing(10)
        self.controlLayout.setObjectName("controlLayout")
        self.logo = QtWidgets.QLabel(ControlSystem)
        self.logo.setMinimumSize(QtCore.QSize(400, 180))
        self.logo.setMaximumSize(QtCore.QSize(400, 180))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("pd3d.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.logo.setObjectName("logo")
        self.controlLayout.addWidget(self.logo)
        self.connectAll = QtWidgets.QPushButton(ControlSystem)
        self.connectAll.setMinimumSize(QtCore.QSize(0, 50))
        self.connectAll.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.connectAll.setFont(font)
        self.connectAll.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.connectAll.setObjectName("connectAll")
        self.controlLayout.addWidget(self.connectAll)
        self.int1All = QtWidgets.QPushButton(ControlSystem)
        self.int1All.setMinimumSize(QtCore.QSize(0, 50))
        self.int1All.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.int1All.setFont(font)
        self.int1All.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.int1All.setObjectName("int1All")
        self.controlLayout.addWidget(self.int1All)
        self.int2All = QtWidgets.QPushButton(ControlSystem)
        self.int2All.setMinimumSize(QtCore.QSize(0, 50))
        self.int2All.setMaximumSize(QtCore.QSize(400, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.int2All.setFont(font)
        self.int2All.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.int2All.setObjectName("int2All")
        self.controlLayout.addWidget(self.int2All)
        self.panelTabs = QtWidgets.QTabWidget(ControlSystem)
        self.panelTabs.setEnabled(True)
        self.panelTabs.setMinimumSize(QtCore.QSize(0, 200))
        self.panelTabs.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.panelTabs.setFont(font)
        self.panelTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.panelTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.panelTabs.setUsesScrollButtons(False)
        self.panelTabs.setObjectName("panelTabs")
        self.p1tab = QtWidgets.QWidget()
        self.p1tab.setObjectName("p1tab")
        self.p1tabLayout = QtWidgets.QVBoxLayout(self.p1tab)
        self.p1tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p1tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p1tabLayout.setSpacing(10)
        self.p1tabLayout.setObjectName("p1tabLayout")
        self.p1addr = QtWidgets.QLabel(self.p1tab)
        self.p1addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p1addr.setFont(font)
        self.p1addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p1addr.setObjectName("p1addr")
        self.p1tabLayout.addWidget(self.p1addr)
        self.p1scrollArea = QtWidgets.QScrollArea(self.p1tab)
        self.p1scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p1scrollArea.setWidgetResizable(True)
        self.p1scrollArea.setObjectName("p1scrollArea")
        self.p1scrollcontents = QtWidgets.QWidget()
        self.p1scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p1scrollcontents.setObjectName("p1scrollcontents")
        self.windowLayout_4 = QtWidgets.QVBoxLayout(self.p1scrollcontents)
        self.windowLayout_4.setObjectName("windowLayout_4")
        self.p1output = QtWidgets.QLabel(self.p1scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1output.sizePolicy().hasHeightForWidth())
        self.p1output.setSizePolicy(sizePolicy)
        self.p1output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p1output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p1output.setObjectName("p1output")
        self.windowLayout_4.addWidget(self.p1output)
        self.p1scrollArea.setWidget(self.p1scrollcontents)
        self.p1tabLayout.addWidget(self.p1scrollArea)
        self.p1addrUpdate = QtWidgets.QPushButton(self.p1tab)
        self.p1addrUpdate.setEnabled(False)
        self.p1addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p1addrUpdate.setFont(font)
        self.p1addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p1addrUpdate.setObjectName("p1addrUpdate")
        self.p1tabLayout.addWidget(self.p1addrUpdate)
        self.panelTabs.addTab(self.p1tab, "")
        self.p2tab = QtWidgets.QWidget()
        self.p2tab.setObjectName("p2tab")
        self.p2tabLayout = QtWidgets.QVBoxLayout(self.p2tab)
        self.p2tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p2tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p2tabLayout.setSpacing(10)
        self.p2tabLayout.setObjectName("p2tabLayout")
        self.p2addr = QtWidgets.QLabel(self.p2tab)
        self.p2addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p2addr.setFont(font)
        self.p2addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p2addr.setObjectName("p2addr")
        self.p2tabLayout.addWidget(self.p2addr)
        self.p2scrollArea = QtWidgets.QScrollArea(self.p2tab)
        self.p2scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p2scrollArea.setWidgetResizable(True)
        self.p2scrollArea.setObjectName("p2scrollArea")
        self.p2scrollcontents = QtWidgets.QWidget()
        self.p2scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p2scrollcontents.setObjectName("p2scrollcontents")
        self.windowLayout_3 = QtWidgets.QVBoxLayout(self.p2scrollcontents)
        self.windowLayout_3.setObjectName("windowLayout_3")
        self.p2output = QtWidgets.QLabel(self.p2scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2output.sizePolicy().hasHeightForWidth())
        self.p2output.setSizePolicy(sizePolicy)
        self.p2output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p2output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p2output.setObjectName("p2output")
        self.windowLayout_3.addWidget(self.p2output)
        self.p2scrollArea.setWidget(self.p2scrollcontents)
        self.p2tabLayout.addWidget(self.p2scrollArea)
        self.p2addrUpdate = QtWidgets.QPushButton(self.p2tab)
        self.p2addrUpdate.setEnabled(False)
        self.p2addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p2addrUpdate.setFont(font)
        self.p2addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p2addrUpdate.setObjectName("p2addrUpdate")
        self.p2tabLayout.addWidget(self.p2addrUpdate)
        self.panelTabs.addTab(self.p2tab, "")
        self.p3tab = QtWidgets.QWidget()
        self.p3tab.setObjectName("p3tab")
        self.p3tabLayout = QtWidgets.QVBoxLayout(self.p3tab)
        self.p3tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p3tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p3tabLayout.setSpacing(10)
        self.p3tabLayout.setObjectName("p3tabLayout")
        self.p3addr = QtWidgets.QLabel(self.p3tab)
        self.p3addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p3addr.setFont(font)
        self.p3addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p3addr.setObjectName("p3addr")
        self.p3tabLayout.addWidget(self.p3addr)
        self.p3scrollArea = QtWidgets.QScrollArea(self.p3tab)
        self.p3scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p3scrollArea.setWidgetResizable(True)
        self.p3scrollArea.setObjectName("p3scrollArea")
        self.p3scrollcontents = QtWidgets.QWidget()
        self.p3scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p3scrollcontents.setObjectName("p3scrollcontents")
        self.windowLayout_5 = QtWidgets.QVBoxLayout(self.p3scrollcontents)
        self.windowLayout_5.setObjectName("windowLayout_5")
        self.p3output = QtWidgets.QLabel(self.p3scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3output.sizePolicy().hasHeightForWidth())
        self.p3output.setSizePolicy(sizePolicy)
        self.p3output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p3output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p3output.setObjectName("p3output")
        self.windowLayout_5.addWidget(self.p3output)
        self.p3scrollArea.setWidget(self.p3scrollcontents)
        self.p3tabLayout.addWidget(self.p3scrollArea)
        self.p3addrUpdate = QtWidgets.QPushButton(self.p3tab)
        self.p3addrUpdate.setEnabled(False)
        self.p3addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p3addrUpdate.setFont(font)
        self.p3addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p3addrUpdate.setObjectName("p3addrUpdate")
        self.p3tabLayout.addWidget(self.p3addrUpdate)
        self.panelTabs.addTab(self.p3tab, "")
        self.p4tab = QtWidgets.QWidget()
        self.p4tab.setObjectName("p4tab")
        self.p4tabLayout = QtWidgets.QVBoxLayout(self.p4tab)
        self.p4tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p4tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p4tabLayout.setSpacing(10)
        self.p4tabLayout.setObjectName("p4tabLayout")
        self.p4addr = QtWidgets.QLabel(self.p4tab)
        self.p4addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p4addr.setFont(font)
        self.p4addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p4addr.setObjectName("p4addr")
        self.p4tabLayout.addWidget(self.p4addr)
        self.p4scrollArea = QtWidgets.QScrollArea(self.p4tab)
        self.p4scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p4scrollArea.setWidgetResizable(True)
        self.p4scrollArea.setObjectName("p4scrollArea")
        self.p4scrollcontents = QtWidgets.QWidget()
        self.p4scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p4scrollcontents.setObjectName("p4scrollcontents")
        self.windowLayout_7 = QtWidgets.QVBoxLayout(self.p4scrollcontents)
        self.windowLayout_7.setObjectName("windowLayout_7")
        self.p4output = QtWidgets.QLabel(self.p4scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p4output.sizePolicy().hasHeightForWidth())
        self.p4output.setSizePolicy(sizePolicy)
        self.p4output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p4output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p4output.setObjectName("p4output")
        self.windowLayout_7.addWidget(self.p4output)
        self.p4scrollArea.setWidget(self.p4scrollcontents)
        self.p4tabLayout.addWidget(self.p4scrollArea)
        self.p4addrUpdate = QtWidgets.QPushButton(self.p4tab)
        self.p4addrUpdate.setEnabled(False)
        self.p4addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p4addrUpdate.setFont(font)
        self.p4addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p4addrUpdate.setObjectName("p4addrUpdate")
        self.p4tabLayout.addWidget(self.p4addrUpdate)
        self.panelTabs.addTab(self.p4tab, "")
        self.p5tab = QtWidgets.QWidget()
        self.p5tab.setObjectName("p5tab")
        self.p5tabLayout = QtWidgets.QVBoxLayout(self.p5tab)
        self.p5tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p5tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p5tabLayout.setSpacing(10)
        self.p5tabLayout.setObjectName("p5tabLayout")
        self.p5addr = QtWidgets.QLabel(self.p5tab)
        self.p5addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p5addr.setFont(font)
        self.p5addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p5addr.setObjectName("p5addr")
        self.p5tabLayout.addWidget(self.p5addr)
        self.p5scrollArea = QtWidgets.QScrollArea(self.p5tab)
        self.p5scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p5scrollArea.setWidgetResizable(True)
        self.p5scrollArea.setObjectName("p5scrollArea")
        self.p5scrollcontents = QtWidgets.QWidget()
        self.p5scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p5scrollcontents.setObjectName("p5scrollcontents")
        self.windowLayout_9 = QtWidgets.QVBoxLayout(self.p5scrollcontents)
        self.windowLayout_9.setObjectName("windowLayout_9")
        self.p5output = QtWidgets.QLabel(self.p5scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p5output.sizePolicy().hasHeightForWidth())
        self.p5output.setSizePolicy(sizePolicy)
        self.p5output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p5output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p5output.setObjectName("p5output")
        self.windowLayout_9.addWidget(self.p5output)
        self.p5scrollArea.setWidget(self.p5scrollcontents)
        self.p5tabLayout.addWidget(self.p5scrollArea)
        self.p5addrUpdate = QtWidgets.QPushButton(self.p5tab)
        self.p5addrUpdate.setEnabled(False)
        self.p5addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p5addrUpdate.setFont(font)
        self.p5addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p5addrUpdate.setObjectName("p5addrUpdate")
        self.p5tabLayout.addWidget(self.p5addrUpdate)
        self.panelTabs.addTab(self.p5tab, "")
        self.p6tab = QtWidgets.QWidget()
        self.p6tab.setObjectName("p6tab")
        self.p6tabLayout = QtWidgets.QVBoxLayout(self.p6tab)
        self.p6tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p6tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p6tabLayout.setSpacing(10)
        self.p6tabLayout.setObjectName("p6tabLayout")
        self.p6addr = QtWidgets.QLabel(self.p6tab)
        self.p6addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p6addr.setFont(font)
        self.p6addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p6addr.setObjectName("p6addr")
        self.p6tabLayout.addWidget(self.p6addr)
        self.p6scrollArea = QtWidgets.QScrollArea(self.p6tab)
        self.p6scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p6scrollArea.setWidgetResizable(True)
        self.p6scrollArea.setObjectName("p6scrollArea")
        self.p6scrollcontents = QtWidgets.QWidget()
        self.p6scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p6scrollcontents.setObjectName("p6scrollcontents")
        self.windowLayout_11 = QtWidgets.QVBoxLayout(self.p6scrollcontents)
        self.windowLayout_11.setObjectName("windowLayout_11")
        self.p6output = QtWidgets.QLabel(self.p6scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p6output.sizePolicy().hasHeightForWidth())
        self.p6output.setSizePolicy(sizePolicy)
        self.p6output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p6output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p6output.setObjectName("p6output")
        self.windowLayout_11.addWidget(self.p6output)
        self.p6scrollArea.setWidget(self.p6scrollcontents)
        self.p6tabLayout.addWidget(self.p6scrollArea)
        self.p6addrUpdate = QtWidgets.QPushButton(self.p6tab)
        self.p6addrUpdate.setEnabled(False)
        self.p6addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p6addrUpdate.setFont(font)
        self.p6addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p6addrUpdate.setObjectName("p6addrUpdate")
        self.p6tabLayout.addWidget(self.p6addrUpdate)
        self.panelTabs.addTab(self.p6tab, "")
        self.p7tab = QtWidgets.QWidget()
        self.p7tab.setObjectName("p7tab")
        self.p7tabLayout = QtWidgets.QVBoxLayout(self.p7tab)
        self.p7tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p7tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p7tabLayout.setSpacing(10)
        self.p7tabLayout.setObjectName("p7tabLayout")
        self.p7addr = QtWidgets.QLabel(self.p7tab)
        self.p7addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p7addr.setFont(font)
        self.p7addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p7addr.setObjectName("p7addr")
        self.p7tabLayout.addWidget(self.p7addr)
        self.p7scrollArea = QtWidgets.QScrollArea(self.p7tab)
        self.p7scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p7scrollArea.setWidgetResizable(True)
        self.p7scrollArea.setObjectName("p7scrollArea")
        self.p7scrollcontents = QtWidgets.QWidget()
        self.p7scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p7scrollcontents.setObjectName("p7scrollcontents")
        self.windowLayout_6 = QtWidgets.QVBoxLayout(self.p7scrollcontents)
        self.windowLayout_6.setObjectName("windowLayout_6")
        self.p7output = QtWidgets.QLabel(self.p7scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p7output.sizePolicy().hasHeightForWidth())
        self.p7output.setSizePolicy(sizePolicy)
        self.p7output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p7output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p7output.setObjectName("p7output")
        self.windowLayout_6.addWidget(self.p7output)
        self.p7scrollArea.setWidget(self.p7scrollcontents)
        self.p7tabLayout.addWidget(self.p7scrollArea)
        self.p7addrUpdate = QtWidgets.QPushButton(self.p7tab)
        self.p7addrUpdate.setEnabled(False)
        self.p7addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p7addrUpdate.setFont(font)
        self.p7addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p7addrUpdate.setObjectName("p7addrUpdate")
        self.p7tabLayout.addWidget(self.p7addrUpdate)
        self.panelTabs.addTab(self.p7tab, "")
        self.p8tab = QtWidgets.QWidget()
        self.p8tab.setObjectName("p8tab")
        self.p8tabLayout = QtWidgets.QVBoxLayout(self.p8tab)
        self.p8tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p8tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p8tabLayout.setSpacing(10)
        self.p8tabLayout.setObjectName("p8tabLayout")
        self.p8addr = QtWidgets.QLabel(self.p8tab)
        self.p8addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p8addr.setFont(font)
        self.p8addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p8addr.setObjectName("p8addr")
        self.p8tabLayout.addWidget(self.p8addr)
        self.p8scrollArea = QtWidgets.QScrollArea(self.p8tab)
        self.p8scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p8scrollArea.setWidgetResizable(True)
        self.p8scrollArea.setObjectName("p8scrollArea")
        self.p8scrollcontents = QtWidgets.QWidget()
        self.p8scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p8scrollcontents.setObjectName("p8scrollcontents")
        self.windowLayout_8 = QtWidgets.QVBoxLayout(self.p8scrollcontents)
        self.windowLayout_8.setObjectName("windowLayout_8")
        self.p8output = QtWidgets.QLabel(self.p8scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p8output.sizePolicy().hasHeightForWidth())
        self.p8output.setSizePolicy(sizePolicy)
        self.p8output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p8output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p8output.setObjectName("p8output")
        self.windowLayout_8.addWidget(self.p8output)
        self.p8scrollArea.setWidget(self.p8scrollcontents)
        self.p8tabLayout.addWidget(self.p8scrollArea)
        self.p8addrUpdate = QtWidgets.QPushButton(self.p8tab)
        self.p8addrUpdate.setEnabled(False)
        self.p8addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p8addrUpdate.setFont(font)
        self.p8addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p8addrUpdate.setObjectName("p8addrUpdate")
        self.p8tabLayout.addWidget(self.p8addrUpdate)
        self.panelTabs.addTab(self.p8tab, "")
        self.p9tab = QtWidgets.QWidget()
        self.p9tab.setObjectName("p9tab")
        self.p9tabLayout = QtWidgets.QVBoxLayout(self.p9tab)
        self.p9tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p9tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p9tabLayout.setSpacing(10)
        self.p9tabLayout.setObjectName("p9tabLayout")
        self.p9addr = QtWidgets.QLabel(self.p9tab)
        self.p9addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p9addr.setFont(font)
        self.p9addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p9addr.setObjectName("p9addr")
        self.p9tabLayout.addWidget(self.p9addr)
        self.p9scrollArea = QtWidgets.QScrollArea(self.p9tab)
        self.p9scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p9scrollArea.setWidgetResizable(True)
        self.p9scrollArea.setObjectName("p9scrollArea")
        self.p9scrollcontents = QtWidgets.QWidget()
        self.p9scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p9scrollcontents.setObjectName("p9scrollcontents")
        self.windowLayout_10 = QtWidgets.QVBoxLayout(self.p9scrollcontents)
        self.windowLayout_10.setObjectName("windowLayout_10")
        self.p9output = QtWidgets.QLabel(self.p9scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p9output.sizePolicy().hasHeightForWidth())
        self.p9output.setSizePolicy(sizePolicy)
        self.p9output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p9output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p9output.setObjectName("p9output")
        self.windowLayout_10.addWidget(self.p9output)
        self.p9scrollArea.setWidget(self.p9scrollcontents)
        self.p9tabLayout.addWidget(self.p9scrollArea)
        self.p9addrUpdate = QtWidgets.QPushButton(self.p9tab)
        self.p9addrUpdate.setEnabled(False)
        self.p9addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p9addrUpdate.setFont(font)
        self.p9addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p9addrUpdate.setObjectName("p9addrUpdate")
        self.p9tabLayout.addWidget(self.p9addrUpdate)
        self.panelTabs.addTab(self.p9tab, "")
        self.p10tab = QtWidgets.QWidget()
        self.p10tab.setObjectName("p10tab")
        self.p10tabLayout = QtWidgets.QVBoxLayout(self.p10tab)
        self.p10tabLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.p10tabLayout.setContentsMargins(5, 5, 5, 5)
        self.p10tabLayout.setSpacing(10)
        self.p10tabLayout.setObjectName("p10tabLayout")
        self.p10addr = QtWidgets.QLabel(self.p10tab)
        self.p10addr.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p10addr.setFont(font)
        self.p10addr.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p10addr.setObjectName("p10addr")
        self.p10tabLayout.addWidget(self.p10addr)
        self.p10scrollArea = QtWidgets.QScrollArea(self.p10tab)
        self.p10scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.p10scrollArea.setWidgetResizable(True)
        self.p10scrollArea.setObjectName("p10scrollArea")
        self.p10scrollcontents = QtWidgets.QWidget()
        self.p10scrollcontents.setGeometry(QtCore.QRect(0, 0, 382, 267))
        self.p10scrollcontents.setObjectName("p10scrollcontents")
        self.windowLayout_12 = QtWidgets.QVBoxLayout(self.p10scrollcontents)
        self.windowLayout_12.setObjectName("windowLayout_12")
        self.p10output = QtWidgets.QLabel(self.p10scrollcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p10output.sizePolicy().hasHeightForWidth())
        self.p10output.setSizePolicy(sizePolicy)
        self.p10output.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p10output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.p10output.setObjectName("p10output")
        self.windowLayout_12.addWidget(self.p10output)
        self.p10scrollArea.setWidget(self.p10scrollcontents)
        self.p10tabLayout.addWidget(self.p10scrollArea)
        self.p10addrUpdate = QtWidgets.QPushButton(self.p10tab)
        self.p10addrUpdate.setEnabled(False)
        self.p10addrUpdate.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.p10addrUpdate.setFont(font)
        self.p10addrUpdate.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.p10addrUpdate.setObjectName("p10addrUpdate")
        self.p10tabLayout.addWidget(self.p10addrUpdate)
        self.panelTabs.addTab(self.p10tab, "")
        self.controlLayout.addWidget(self.panelTabs)
        self.optionsLayout = QtWidgets.QHBoxLayout()
        self.optionsLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.optionsLayout.setSpacing(10)
        self.optionsLayout.setObjectName("optionsLayout")
        self.advancedOpt = QtWidgets.QToolButton(ControlSystem)
        self.advancedOpt.setMinimumSize(QtCore.QSize(75, 75))
        self.advancedOpt.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.advancedOpt.setFont(font)
        self.advancedOpt.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.advancedOpt.setObjectName("advancedOpt")
        self.optionsLayout.addWidget(self.advancedOpt)
        self.quitProg = QtWidgets.QPushButton(ControlSystem)
        self.quitProg.setMinimumSize(QtCore.QSize(75, 75))
        self.quitProg.setMaximumSize(QtCore.QSize(350, 75))
        self.quitProg.setStyleSheet("background: rgba(240, 240, 240, 220);")
        self.quitProg.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("powerbutton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitProg.setIcon(icon)
        self.quitProg.setIconSize(QtCore.QSize(50, 50))
        self.quitProg.setObjectName("quitProg")
        self.optionsLayout.addWidget(self.quitProg)
        self.controlLayout.addLayout(self.optionsLayout)
        self.primaryGrid.addLayout(self.controlLayout, 0, 0, 3, 1)
        self.windowLayout.addLayout(self.primaryGrid)

        self.initTranslateUI(ControlSystem)
        self.panelTabs.setCurrentIndex(9)
        self.quitProg.clicked.connect(ControlSystem.close)
        #QtCore.QMetaObject.connectSlotsByName(ControlSystem)

    def initTranslateUI(self, ControlSystem):
        _translate = QtCore.QCoreApplication.translate
        ControlSystem.setWindowTitle(_translate("ControlSystem", "Panel Control System"))

        self.room1.setText(_translate("ControlSystem", "Room 1"))
        self.StatusR1.setText(_translate("ControlSystem", "Connect"))
        self.Int1R1.setText(_translate("ControlSystem", "Int: 1"))
        self.Int2R1.setText(_translate("ControlSystem", "Int: 2"))
        self.selectPanelR1.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.selectPanelR1.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.selectPanelR1.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.selectPanelR1.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.selectPanelR1.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.selectPanelR1.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.selectPanelR1.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.selectPanelR1.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.selectPanelR1.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.selectPanelR1.setItemText(9, _translate("ControlSystem", "Panel 10"))

        self.room2.setText(_translate("ControlSystem", "Room 2"))
        self.p2Status.setText(_translate("ControlSystem", "Connect"))
        self.p2Int1.setText(_translate("ControlSystem", "Int: 1"))
        self.p2Int2.setText(_translate("ControlSystem", "Int: 2"))
        self.p2SelectPanel.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.p2SelectPanel.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.p2SelectPanel.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.p2SelectPanel.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.p2SelectPanel.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.p2SelectPanel.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.p2SelectPanel.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.p2SelectPanel.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.p2SelectPanel.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.p2SelectPanel.setItemText(9, _translate("ControlSystem", "Panel 10"))

        self.room3.setText(_translate("ControlSystem", "Room 3"))
        self.p3Status.setText(_translate("ControlSystem", "Connect"))
        self.p3Int1.setText(_translate("ControlSystem", "Int: 1"))
        self.p3Int2.setText(_translate("ControlSystem", "Int: 2"))
        self.p3SelectPanel.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.p3SelectPanel.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.p3SelectPanel.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.p3SelectPanel.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.p3SelectPanel.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.p3SelectPanel.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.p3SelectPanel.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.p3SelectPanel.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.p3SelectPanel.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.p3SelectPanel.setItemText(9, _translate("ControlSystem", "Panel 10"))

        self.room4.setText(_translate("ControlSystem", "Room 4"))
        self.p4Status.setText(_translate("ControlSystem", "Connect"))
        self.p4Int1.setText(_translate("ControlSystem", "Int: 1"))
        self.p4Int2.setText(_translate("ControlSystem", "Int: 2"))
        self.p4SelectPanel.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.p4SelectPanel.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.p4SelectPanel.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.p4SelectPanel.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.p4SelectPanel.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.p4SelectPanel.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.p4SelectPanel.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.p4SelectPanel.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.p4SelectPanel.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.p4SelectPanel.setItemText(9, _translate("ControlSystem", "Panel 10"))

        self.room5.setText(_translate("ControlSystem", "Room 5"))
        self.p5Status.setText(_translate("ControlSystem", "Connect"))
        self.p5Int1.setText(_translate("ControlSystem", "Int: 1"))
        self.p5Int2.setText(_translate("ControlSystem", "Int: 2"))
        self.p5SelectPanel.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.p5SelectPanel.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.p5SelectPanel.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.p5SelectPanel.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.p5SelectPanel.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.p5SelectPanel.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.p5SelectPanel.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.p5SelectPanel.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.p5SelectPanel.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.p5SelectPanel.setItemText(9, _translate("ControlSystem", "Panel 10"))


        self.room6.setText(_translate("ControlSystem", "Room 6"))
        self.p6Status.setText(_translate("ControlSystem", "Connect"))
        self.p6Int1.setText(_translate("ControlSystem", "Int: 1"))
        self.p6Int2.setText(_translate("ControlSystem", "Int: 2"))
        self.p6SelectPanel.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.p6SelectPanel.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.p6SelectPanel.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.p6SelectPanel.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.p6SelectPanel.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.p6SelectPanel.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.p6SelectPanel.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.p6SelectPanel.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.p6SelectPanel.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.p6SelectPanel.setItemText(9, _translate("ControlSystem", "Panel 10"))

        self.room7.setText(_translate("ControlSystem", "Room 7"))
        self.p7Status.setText(_translate("ControlSystem", "Connect"))
        self.p7Int1.setText(_translate("ControlSystem", "Int: 1"))
        self.p7Int2.setText(_translate("ControlSystem", "Int: 2"))
        self.p7SelectPanel.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.p7SelectPanel.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.p7SelectPanel.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.p7SelectPanel.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.p7SelectPanel.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.p7SelectPanel.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.p7SelectPanel.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.p7SelectPanel.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.p7SelectPanel.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.p7SelectPanel.setItemText(9, _translate("ControlSystem", "Panel 10"))

        self.room8.setText(_translate("ControlSystem", "Room 8"))
        self.p8Status.setText(_translate("ControlSystem", "Connect"))
        self.p8Int1.setText(_translate("ControlSystem", "Int: 1"))
        self.p8Int2.setText(_translate("ControlSystem", "Int: 2"))
        self.p8SelectPanel.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.p8SelectPanel.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.p8SelectPanel.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.p8SelectPanel.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.p8SelectPanel.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.p8SelectPanel.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.p8SelectPanel.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.p8SelectPanel.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.p8SelectPanel.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.p8SelectPanel.setItemText(9, _translate("ControlSystem", "Panel 10"))

        self.room9.setText(_translate("ControlSystem", "Room 9"))
        self.p9Status.setText(_translate("ControlSystem", "Connect"))
        self.p9Int1.setText(_translate("ControlSystem", "Int: 1"))
        self.p9Int2.setText(_translate("ControlSystem", "Int: 2"))
        self.p9SelectPanel.setItemText(0, _translate("ControlSystem", "Panel 1"))
        self.p9SelectPanel.setItemText(1, _translate("ControlSystem", "Panel 2"))
        self.p9SelectPanel.setItemText(2, _translate("ControlSystem", "Panel 3"))
        self.p9SelectPanel.setItemText(3, _translate("ControlSystem", "Panel 4"))
        self.p9SelectPanel.setItemText(4, _translate("ControlSystem", "Panel 5"))
        self.p9SelectPanel.setItemText(5, _translate("ControlSystem", "Panel 6"))
        self.p9SelectPanel.setItemText(6, _translate("ControlSystem", "Panel 7"))
        self.p9SelectPanel.setItemText(7, _translate("ControlSystem", "Panel 8"))
        self.p9SelectPanel.setItemText(8, _translate("ControlSystem", "Panel 9"))
        self.p9SelectPanel.setItemText(9, _translate("ControlSystem", "Panel 10"))

        self.connectAll.setText(_translate("ControlSystem", "Connect All"))
        self.int1All.setText(_translate("ControlSystem", "Interaction 1"))
        self.int2All.setText(_translate("ControlSystem", "Interaction 2"))

        self.p1addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p1output.setText(_translate("ControlSystem", "Output..."))
        self.p1addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p1tab), _translate("ControlSystem", "P1"))

        self.p2addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p2output.setText(_translate("ControlSystem", "Output..."))
        self.p2addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p2tab), _translate("ControlSystem", "P2"))

        self.p3addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p3output.setText(_translate("ControlSystem", "Output..."))
        self.p3addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p3tab), _translate("ControlSystem", "P3"))

        self.p4addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p4output.setText(_translate("ControlSystem", "Output..."))
        self.p4addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p4tab), _translate("ControlSystem", "P4"))

        self.p5addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p5output.setText(_translate("ControlSystem", "Output..."))
        self.p5addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p5tab), _translate("ControlSystem", "P5"))

        self.p6addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p6output.setText(_translate("ControlSystem", "Output..."))
        self.p6addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p6tab), _translate("ControlSystem", "P6"))

        self.p7addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p7output.setText(_translate("ControlSystem", "Output..."))
        self.p7addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p7tab), _translate("ControlSystem", "P7"))

        self.p8addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p8output.setText(_translate("ControlSystem", "Output..."))
        self.p8addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p8tab), _translate("ControlSystem", "P8"))

        self.p9addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p9output.setText(_translate("ControlSystem", "Output..."))
        self.p9addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p9tab), _translate("ControlSystem", "P9"))

        self.p10addr.setText(_translate("ControlSystem", "IP Address:"))
        self.p10output.setText(_translate("ControlSystem", "Output..."))
        self.p10addrUpdate.setText(_translate("ControlSystem", "Manually Update IP Address"))
        self.panelTabs.setTabText(self.panelTabs.indexOf(self.p10tab), _translate("ControlSystem", "P10"))

        self.advancedOpt.setText(_translate("ControlSystem", "Adv.\nOptions"))
        self.quitProg.setShortcut(_translate("ControlSystem", "Ctrl+C"))

# -------------------------------------------------------------------------------------------------------- #
if __name__ == "__main__":
    print("Initializing...")
    appplication = QtWidgets.QApplication(sys.argv)
    appplication.setStyle('Fusion')

    ControlSystem = QtWidgets.QWidget()
    window = GUI(ControlSystem)
    ControlSystem.show()

    sys.exit(appplication.exec_())
